### PR TITLE
Fs verity

### LINKED ISSUE #69: Add [dm|fs] verity support to puzzlefs
We need some research into https://github.com/containers/composefs first and then reason how to go about this.

### PR DESCRIPTION
**Pull request by ariel-miculas**
Fixes #69

### CODE REVIEW

**Comment by hallyn** [comment]
Hm, when i run the tests locally, i get 

```
test build_and_extract_is_noop ... FAILED
```

**Comment by hallyn** [comment]
set looks good, though.  I'll approve now, you can decide whether to merge or look into that failure.  may well be just a local weird issue here.

**Review by hallyn — APPROVED** [review]

**Comment by ariel-miculas** [comment]
@hallyn I can't reproduce your issue, did you run `docker pull ubuntu` beforehand?

**Comment by hallyn** [comment]
> @hallyn I can't reproduce your issue, did you run `docker pull ubuntu` beforehand?

No, I don't have docker.

**Comment by ariel-miculas** [comment]
Then the test will fail until #68 is implemented

**Pull request merged**
